- platform: speedtest
  hour:
    - 8
    - 12
    - 16
    - 20
  monitored_conditions:
    - ping
    - download
    - upload

- platform: steam_online
  api_key: N/A
  accounts:
    - N/A
    - N/A

- platform: command_line
  command: sudo python /home/pi/Desktop/LightLevel.py
  name: Light Level