### AUTOMATION ###

# Sky #
- alias: 'BBC One'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'BBC One'
  action:
    service: shell_command.bbcone
- alias: 'BBC Two'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'BBC Two'
  action:
    service: shell_command.bbctwo
- alias: 'ITV'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'ITV'
  action:
    service: shell_command.itv
- alias: 'Channel 4'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'Channel 4'
  action:
    service: shell_command.channel4
- alias: 'Sky 1'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'Sky 1'
  action:
    service: shell_command.sky1
# Player Online
- alias: 'Player Online'
  trigger:
    - platform: state
      entity_id: sensor.pickcraft
      state: '1/15'
  action:
    service: switch.turn_on
    entity_id: switch.green
- alias: 'Player Online'
  trigger:
    - platform: state
      entity_id: sensor.pickcraft
      state: '2/15'
  action:
    service: switch.turn_on
    entity_id: switch.green
- alias: 'Player Online'
  trigger:
    - platform: state
      entity_id: sensor.pickcraft
      state: '3/15'
  action:
    service: switch.turn_on
    entity_id: switch.green
- alias: 'Player Online'
  trigger:
    - platform: state
      entity_id: sensor.pickcraft
      state: '0/15'
  action:
    service: switch.turn_off
    entity_id: switch.green