### CONFIGURATION ###

## GENERAL ##
homeassistant:
  name: Stuff
  latitude: N/A
  longitude: N/A
  temperature_unit: C
  time_zone: Europe/London
  customize: !include customize.yaml

## INCLUDE ##
# Devices #
switch: !include devices/switches.yaml
sensor: !include devices/sensors.yaml
media_player: !include devices/media_players.yaml
camera: !include devices/cameras.yaml
# Inputs #
input_select: !include inputs/input_select.yaml
input_slider: !include inputs/input_slider.yaml
# Web Links #
weblink: !include web_links.yaml
# Shell Commands #
shell_command: !include shell_commands.yaml
# Scripts #
script: !include scripts.yaml
# Groups #
group: !include groups.yaml
# Automation #
automation: !include automation.yaml

## Bart's Pokemon Platform ##
pokemon:
  playername: GreenTurtwig
  enemyname: Bart274

## ACTIVATE ##
history:
frontend: