homeassistant:
  name: N/A
  latitude: N/A
  longitude: N/A
  temperature_unit: C
  time_zone: Europe/London
  customize: !include customize.yaml
  
group: !include groups.yaml
automation: !include automation.yaml

media_player: !include devices/media_players.yaml
sensor: !include devices/sensors.yaml
switch: !include devices/switches.yaml

input_select:
  channel:
    name: Channel
    options:
      - BBC One
      - BBC Two
      - ITV
      - Channel 4
      - Sky 1
    initial: BBC One
    icon: mdi:television-guide
  station:
    name: Station
    options:
      - BBC Radio Berkshire
      - BBC Radio Two
      - Heart
    initial: BBC Radio Berkshire
    icon: mdi:radio-tower

weblink:
  entities:
    - name: Router
      url: http://192.168.0.1

shell_command: !include shell_commands.yaml
script: !include scripts.yaml

frontend:

